### ISSUE TITLE
Cart styling is off

### ISSUE THREAD

**Issue by prasunbhunia** [Visoneers/Pinaka#1]
![Screenshot (254)](https://user-images.githubusercontent.com/65885986/97865019-88292b80-1d2f-11eb-96d2-bf1187ceb677.png)

However, I believe it should look like this

![Screenshot (255)](https://user-images.githubusercontent.com/65885986/97865321-07b6fa80-1d30-11eb-9497-0e88618c491c.png)

**Comment by aniket2666** [comment]
No problem, let's see
